project_name: acast

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - "386"
      - arm
      - mips
      - mipsle
      - mips64
      - mips64le
      - ppc64
      - ppc64le
      - s390x
      - riscv64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: mips
      - goos: darwin
        goarch: mipsle
      - goos: darwin
        goarch: mips64
      - goos: darwin
        goarch: mips64le
      - goos: darwin
        goarch: ppc64
      - goos: darwin
        goarch: ppc64le
      - goos: darwin
        goarch: s390x
      - goos: darwin
        goarch: riscv64
      - goos: windows
        goarch: "386"
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: mips
      - goos: windows
        goarch: mipsle
      - goos: windows
        goarch: mips64
      - goos: windows
        goarch: mips64le
      - goos: windows
        goarch: ppc64
      - goos: windows
        goarch: ppc64le
      - goos: windows
        goarch: s390x
      - goos: windows
        goarch: riscv64
      - goos: darwin
        goarm: "5"
      - goos: darwin
        goarm: "6"
      - goos: darwin
        goarm: "7"
      - goos: windows
        goarm: "5"
      - goos: windows
        goarm: "6"
      - goos: windows
        goarm: "7"
    main: ./cmd/acast
    binary: acast
    ldflags:
      - "-X main.GitTag={{.Tag}} -X main.GitHash={{.ShortCommit}} -s -w"

archives:
  - format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}_v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch 